#!/usr/bin/env bash
# SSH Config File

Host *
	Hostname 52.201.220.52
	User ubuntu
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	GSSAPIAuthentication yes
	[O
	GSSAPIDelegateCredentials no
